name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - name: Get Python 3.8
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.8'

      - name: Configure pip cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt

      - name: Update README file with retry
        run: |
          n=0
          until [ "$n" -ge 5 ]; do
            python daily.py && break
            n=$((n+1))
            echo "Retry #$n..."
            sleep 10
          done
        shell: bash

      - name: Push changes
        run: |
          git config --global user.name "pyoneerC/GitHub-Actions-Bot"
          git config --global user.email "github-actions-bot@pyoneerc.github.io" 
          git add .
          git diff
          git commit -m "Update README" -a || echo "No changes to commit"
          git push

      - name: Send Push Notification
        uses: techulus/push-github-action@1.2.1
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TITLE: Profile README
          MESSAGE: "README updated"
          SOUND: scifi