version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/cache"
    schedule:
      interval: "daily"
    file: "requirements.txt"
